name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Lint and test coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Generate coverage report
        run: |
          pip install pytest coverage jupyter
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi        
          coverage run -m pytest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2      
